### ISSUE TITLE
Home Assistant 2023.8.3 не запускается служба graph_image.create_graph_image

### ISSUE THREAD

**Issue by BertTomsk** [malinovsku/ha-graph-image#2]
Добрый день! 
Установил интеграцию v0.0.8 через HACS, перезагрузил ha, но служба graph_image.create_graph_image почему-то не работает, система говорит, что её не существует. Пробовал переустанавливать, устанавливать вручную, но так и не заводится.

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Пользовательский интерфейс 20230802.1 - latest

Error in describing action: Cannot read properties of undefined (reading 'create_graph_image')
Stopped because an error was encountered at 24 августа 2023 г. в 16:32:39 (runtime: 0.00 seconds)
Unable to find service graph_image.create_graph_image

В автоматизации "Новая автоматизация" (automation.novaia_avtomatizatsiia) используется действие, которое вызывает неизвестную службу: graph_image.create_graph_image.
Это может препятствовать корректному выполнению автоматизации. Возможно, эта служба больше недоступна, а возможно, причиной стала опечатка.
Чтобы исправить эту ошибку, отредактируйте автоматизацию или удалите действие, вызывающее эту службу.
![photo_2023-08-24_18-19-23](https://github.com/malinovsku/ha-graph-image/assets/62449149/0f0bec44-3e70-4ee9-9903-a4427b43ff65)

**Comment by malinovsku** [comment]
@BertTomsk Подскажите, добавили ли вы интеграцию в Настройки->Устройства и службы->Интеграции ? Есть ли в логах ошибки связанные с graph_image при загрузке HA?

**Comment by BertTomsk** [comment]
Это я значит описание плохо читал, не понял что в настройках надо интеграцию добавить ещё. Спасибо большое, вопрос закрыт!
